chore: support the extended readiness check
oauth2-proxy/manifests pull request #113
Opened 2022-10-17 10:30 UTC by kobim

Following https://github.com/oauth2-proxy/oauth2-proxy/pull/1839, this will add the **non-breaking** support for the extended healthcheck as a `readinessProbe`.

2022-10-17 12:33 UTC, pierluigilenoci commented
@kobim this is not enough, you need to bump also the chart version.

2022-10-18 12:29 UTC, pierluigilenoci commented
@kobim if this PR is ready please mark it "Ready for review"

2022-11-15 16:37 UTC, pierluigilenoci commented
@kobim could you please take a look?

2022-11-15 18:46 UTC, kobim commented
@pierluigilenoci I'm still waiting to complete and merge https://github.com/oauth2-proxy/oauth2-proxy/pull/1839 before marking this as ready.

2022-12-23 09:40 UTC, pierluigilenoci commented
@kobim the other PR is merged, can you please follow up on this?

2022-12-23 10:43 UTC, pierluigilenoci approved these changes

2022-12-25 00:01 UTC, pierluigilenoci requested changes

2022-12-25 00:01 UTC, pierluigilenoci commented on helm/oauth2-proxy/templates/deployment.yaml
> +            path: {{ gt .Chart.AppVersion "7.4.0" }}/ready{{ else }}/ping{{ end }}
The real software version is generated in this way:
```
{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}
```

2022-12-27 15:11 UTC, pierluigilenoci commented on helm/oauth2-proxy/templates/_helpers.tpl
> +{{- end -}}
A new line here is missing.

2022-12-27 15:12 UTC, pierluigilenoci approved these changes

2022-12-27 15:17 UTC, merged