Set https port to 4443
oauth2-proxy/manifests pull request #117
Opened 2022-11-01 20:55 UTC by Palollo

Default port for https was 443 ([ref](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/docs/configuration/overview.md?plain=1#L126)) but it is not allowed for binding by a non-root user.
This is what occurs in the default image of this helm chart, so this is a fix for an error appeared when the value "httpScheme" is set to "https".

2022-11-08 10:47 UTC, desaintmartin commented
Indeed. It is similar to https://github.com/oauth2-proxy/manifests/pull/117 but takes a more pragmatic approach. I 117 does not progress in a few days, let's merge this one.

2022-11-08 10:47 UTC, desaintmartin requested changes
Could you bump version in chart.yaml?

2022-11-08 20:14 UTC, Palollo commented
> Indeed. It is similar to #117 but takes a more pragmatic approach. I 117 does not progress in a few days, let's merge this one.

I think you mean #89. I doubt that PR will work well: changing the container port is not enought for that he wants to. He forgot to change:
 - the app port in the "args" of the container (params "--http-address" and "--https-address") in deployment.yaml
 - and also the `targetPort` in the service.yaml file. 
If he is interested yet, he will see the mention here. I can add suggesting changes for clarification in his PR or include his changes in my PR with the needed additions.

> Could you bump version in chart.yaml?

Sure, it's done ;)

2022-11-09 15:32 UTC, desaintmartin commented
Let's merge this, it's easy to rebase in #89 when needed to make it configurable.

2022-11-09 15:52 UTC, desaintmartin approved these changes

2022-11-09 15:52 UTC, merged