Add appProtocol to Service Ports
oauth2-proxy/manifests pull request #123
Opened 2022-12-02 12:44 UTC by shaardie

This patch adds the appProtocol fields to the service ports. Some tools, like istio's service mesh are using those to specify how to handle the traffic.

Signed-off-by: Sven Haardiek <sven.haardiek@uni-muenster.de>

2022-12-05 09:42 UTC, pierluigilenoci commented
@desaintmartin could you please take a look?

2022-12-08 14:17 UTC, pierluigilenoci requested changes

2022-12-08 15:02 UTC, shaardie commented on helm/oauth2-proxy/templates/service.yaml
> +      appProtocol: http
Can this be something else in oauth2-proxy?

2022-12-09 09:07 UTC, pierluigilenoci commented on helm/oauth2-proxy/templates/service.yaml
> +      appProtocol: http
It depends, for example, if you inject a sidecar into the pod that might change.

2022-12-09 12:16 UTC, shaardie commented on helm/oauth2-proxy/templates/service.yaml
> +      appProtocol: http
funnily enough, this is exactly why I introduced this. We are using the istio cluster mesh and it identifies the kind of traffic either based on the prefixed name (e.g. http-something) or on `appProtocol`. Istio works perfectly with setting this to http and itself is hijacking the connection and introducing mtls.

That said, I am perfectly fine with making it configurable (and set the default to http(?)), if this means that we can get this upstream and have not to patch this into the helm chart ourself.

2022-12-12 09:42 UTC, pierluigilenoci commented on helm/oauth2-proxy/templates/service.yaml
> +      appProtocol: http
Please set the default as `http`

2022-12-16 10:36 UTC, pierluigilenoci approved these changes

2022-12-16 10:39 UTC, pierluigilenoci commented
@shaardie I just realized now that the revision of the [README.md](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/README.md) is missing. 
Please add the new parameter in the documentation.

2022-12-16 13:17 UTC, shaardie commented
@pierluigilenoci I missed that. But added it now.

2022-12-20 16:51 UTC, pierluigilenoci submitted a review, later dismissed

2022-12-21 08:39 UTC, shaardie commented
I updated the Chart and resolved the merge conflicts.

2022-12-21 09:58 UTC, pierluigilenoci approved these changes

2022-12-21 10:06 UTC, merged