Add extraContainers: [] configuration option
oauth2-proxy/manifests pull request #138
Opened 2023-03-09 14:57 UTC by illrill

Add `extraContainers: []` configuration option to the chart, so that it's possible to insert a sidecar container. Could for example be useful to achieve setups like [this](https://www.callumpember.com/Kubernetes-A-Single-OAuth2-Proxy-For-Multiple-Ingresses/).

2023-03-09 16:53 UTC, pierluigilenoci requested changes

2023-03-09 16:53 UTC, pierluigilenoci commented on helm/oauth2-proxy/Chart.yaml
> +version: 6.9.2
This is a new feature, so please bump the minor instead.

2023-03-09 16:53 UTC, pierluigilenoci commented
@illrill, thank you for your contribution.

2023-03-09 18:35 UTC, illrill commented
> @illrill, thank you for your contribution.

Thanks for handling the version update! I accidentally removed the review request from @desaintmartin while I was trying to reset your request for change.

2023-03-10 09:13 UTC, pierluigilenoci approved these changes

2023-03-10 09:17 UTC, merged